name: Build DummyApp

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy-flavor:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 5

      - name: Build App
        run: |
          export LANG=en_US.UTF-8
          xcodebuild -scheme DummyApp -configuration Debug