name: Log Metrics
on:
  workflow_run:
    workflows: [Build DummyApp]
    types:
      - completed

jobs:
  log-metrics:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 1

      - name: Log Metrics
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'
        run: |
          swift run Metrics \
              streckenagent \
              "${{ github.event.workflow_run.run_started_at }}" \
              "${{ github.event.workflow_run.conclusion }}" \
              "${{ github.event.workflow_run.updated_at }}"